[Settings]
# The language used for Random Words generation.
# Supported languages: english, portuguese
language = english

# Default time limit in minutes (if not specified via -t in CLI)
default_time = 10

[StandardMode]
# Modes that will be randomly shuffled during a 'standard' session.
# Available options: random_drill, palace_rush, palace_rush_reverse, even_run, odd_run
included_modes = random_drill, palace_rush, palace_rush_reverse, even_run, odd_run
